- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"
- name: "priority: critical"
  description: "Critical priority level"
  color: "7F1146"
- name: "priority: high"
  description: "High priority level"
  color: "F84308"
- name: "priority: low"
  description: "Low priority level"
  color: "5FF465"
- name: "priority: medium"
  description: "Medium priority level"
  color: "D39171"
- name: "status: approved"
  description: "This has been approved"
  color: "11008B"
- name: "status: can't reproduce"
  description: "This is unable to be reproduced"
  color: "1F0430"
- name: "status: duplicate"
  description: "A duplicate exists"
  color: "F56BB9"
- name: "status: needs information"
  description: "This is currently in need of information"
  color: "FD8096"
- name: "status: needs work"
  description: "This still needs some more work"
  color: "B96911"
- name: "status: on hold"
  description: "This is currently on hold"
  color: "B9A9F2"
- name: "status: unapproved"
  description: "This has been unapproved in a projectteam review"
  color: "C9241F"
- name: "status: won't do/fix"
  description: "This won't be done/fixed"
  color: "6455D2"
- name: "type: backlog item"
  description: "This is a backlog item and belongs to a project"
  color: "78F9D7"
- name: "type: bug"
  description: "This is a bug"
  color: "F18257"
- name: "type: documentation"
  description: "This is an addition or improvement to documentation"
  color: "ED1294"
- name: "type: enhancement"
  description: "This is an addition or improvement"
  color: "CF4A7D"
- name: "type: epic"
  description: "This is an epic that contain sub-tasks"
  color: "68F090"
- name: "type: feature/request"
  description: "This is a new feature or request"
  color: "3C1BE2"
- name: "type: sub-task"
  description: "This is a sub-task of an epic"
  color: "bfd4f2"
- name: "size: major"
  description: "A large and significant task or component"
  color: "D7AEF2"
- name: "size: moderate"
  description: "A task or component of intermediate size"
  color: "EBE421"
- name: "size: minor"
  description: "A smaller, less complex task or component"
  color: "82F502"
- name: "size: minimal"
  description: "A very small task or component, requiring minimal effort"
  color: "42DDBF"
