name: Compairifuel Automatic Label Sync Action

on:
  workflow_call:

jobs:
  label-sync:
    name: Label sync
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          sparse-checkout: .github/labels.yml
          sparse-checkout-cone-mode: false
          repository: Compairifuel/.github
      - name: Run Label Sync
        uses: compairifuel/.github/actions/labelsync@main
